### ISSUE TITLE
python3 required

### ISSUE THREAD

**Issue by elvis2** [jameno/Simple-Apple-Health-XML-to-CSV#1]
Thanks for your contribution. You might want to update the readme or docs to make sure folks know that python3 is required. On the MacOS, python2.7 is the default version, which means typing in "python --version" will get the version for 2.7.

Once I installed pandas for pip3 and ran the file with python3, everything ran fine.

Thanks!

**Comment by jameno** [comment]
Hi Elvis, I've updated my README to specific Python 3 and pip3 in commit https://github.com/jameno/Simple-Apple-Health-XML-to-CSV/commit/fd617a5b3f180fb9a0cd9a9defe5452b5cffaaf1

Thank you for helping make the instructions more clear!
