### ISSUE TITLE
Memory errors on large XML files

### ISSUE THREAD

**Issue by jjf112** [jameno/Simple-Apple-Health-XML-to-CSV#5]
My file is 1.1GB

➜  apple_health_export python3 apple_health_xml_convert.py export.xml
Pre-processing...done!
Converting XML File to CSV...Traceback (most recent call last):
  File "/Users/jay/Downloads/apple_health_export/apple_health_xml_convert.py", line 145, in <module>
    main()
  File "/Users/jay/Downloads/apple_health_export/apple_health_xml_convert.py", line 137, in main
    health_df = xml_to_csv(xml_string)
  File "/Users/jay/Downloads/apple_health_export/apple_health_xml_convert.py", line 65, in xml_to_csv
    etree = ET.ElementTree(ET.fromstring(xml_string))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/xml/etree/ElementTree.py", line 1344, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: out of memory: line 1, column 0

**Comment by chkpnt** [comment]
I can confirm this behaviour.

**Comment by jameno** [comment]
#6 may have fixed these issues

@jjf112  @chkpnt Please let me know if this is working for you now

**Comment by chkpnt** [comment]
Thank you, it's working fine! :-)

Had to `pip install memory_profiler`, you may want to update the README.md.

This is the output for my `Export.xml`, which is 1.5 GiB in size:

```
Pre-processing and writing to temporary file...done!
Converting XML File to CSV...done!
Saving CSV file...done!
Removing temporary file...done!
Filename: /Users/ich/Downloads/apple_health_export 4/./apple_health_xml_convert.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
   144     61.3 MiB     61.3 MiB           1   @profile
   145                                         def main():
   146     61.3 MiB      0.0 MiB           1       file_path = "export.xml"
   147     49.9 MiB    -11.3 MiB           1       temp_file_path = preprocess_to_temp_file(file_path)
   148   4203.9 MiB   4154.0 MiB           1       health_df = xml_to_csv(temp_file_path)
   149   5050.1 MiB    846.2 MiB           1       save_to_csv(health_df)
   150   4888.7 MiB   -161.4 MiB           1       remove_temp_file(temp_file_path)
   151
   152   4888.8 MiB      0.0 MiB           1       return
```

**Comment by jameno** [comment]
Ah, I knew I had forgotten something! Thanks for catching this @chkpnt! I've removed the dependency.
